### ISSUE TITLE
Simpler but dumber?

### ISSUE THREAD

**Issue by karlpokus** [peterjaric/mathemancy.js#1]
This is fun! I made a simpler implementation that works for both single-, and multiple digits and the four common operators. Although you have to pass the string to a function though (and that is hard stuff).

```javascript
function epicMath(str) {
  var wordMap = {one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, plus: '+', minus: '-', times: '*', dividedBy: '/'};
  var mappedString = str.split('.').map(function(item){return wordMap[item]}).join('');
  return eval(mappedString);
}
// works with 'six.one.five.plus.two' and 'four.five.six.times.three.dividedby.five'
```

**Comment by peterjaric** [comment]
The current implementation actually supports this already! :) I tried your examples now, just to be sure, and they worked (after changing the dividedby to dividedBy). Also, the warping of the property access notation was kind of the point of my take on this.

So, I'll close the PR, but thanks for giving some attention to this silly project!

**Comment by karlpokus** [comment]
> the warping of the property access notation

Lots of words. Awesome!
